// Generated by gencpp from file softcon/taskVal.msg
// DO NOT EDIT!


#ifndef SOFTCON_MESSAGE_TASKVAL_H
#define SOFTCON_MESSAGE_TASKVAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace softcon
{
template <class ContainerAllocator>
struct taskVal_
{
  typedef taskVal_<ContainerAllocator> Type;

  taskVal_()
    : thrust_factor(0)
    , yaw_setpoint(0)
    , depth_setpoint(0)
    , speed_change(0)  {
    }
  taskVal_(const ContainerAllocator& _alloc)
    : thrust_factor(0)
    , yaw_setpoint(0)
    , depth_setpoint(0)
    , speed_change(0)  {
  (void)_alloc;
    }



   typedef int32_t _thrust_factor_type;
  _thrust_factor_type thrust_factor;

   typedef int32_t _yaw_setpoint_type;
  _yaw_setpoint_type yaw_setpoint;

   typedef int32_t _depth_setpoint_type;
  _depth_setpoint_type depth_setpoint;

   typedef int32_t _speed_change_type;
  _speed_change_type speed_change;





  typedef boost::shared_ptr< ::softcon::taskVal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::softcon::taskVal_<ContainerAllocator> const> ConstPtr;

}; // struct taskVal_

typedef ::softcon::taskVal_<std::allocator<void> > taskVal;

typedef boost::shared_ptr< ::softcon::taskVal > taskValPtr;
typedef boost::shared_ptr< ::softcon::taskVal const> taskValConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::softcon::taskVal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::softcon::taskVal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace softcon

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'softcon': ['/home/kartikay/Desktop/old-stack/oldstack/src/softcon/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::softcon::taskVal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::softcon::taskVal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::softcon::taskVal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::softcon::taskVal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::softcon::taskVal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::softcon::taskVal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::softcon::taskVal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34eb4660468f98f5c19094fca75c6145";
  }

  static const char* value(const ::softcon::taskVal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34eb4660468f98f5ULL;
  static const uint64_t static_value2 = 0xc19094fca75c6145ULL;
};

template<class ContainerAllocator>
struct DataType< ::softcon::taskVal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "softcon/taskVal";
  }

  static const char* value(const ::softcon::taskVal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::softcon::taskVal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 thrust_factor\n\
int32 yaw_setpoint\n\
int32 depth_setpoint\n\
int32 speed_change\n\
";
  }

  static const char* value(const ::softcon::taskVal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::softcon::taskVal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.thrust_factor);
      stream.next(m.yaw_setpoint);
      stream.next(m.depth_setpoint);
      stream.next(m.speed_change);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct taskVal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::softcon::taskVal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::softcon::taskVal_<ContainerAllocator>& v)
  {
    s << indent << "thrust_factor: ";
    Printer<int32_t>::stream(s, indent + "  ", v.thrust_factor);
    s << indent << "yaw_setpoint: ";
    Printer<int32_t>::stream(s, indent + "  ", v.yaw_setpoint);
    s << indent << "depth_setpoint: ";
    Printer<int32_t>::stream(s, indent + "  ", v.depth_setpoint);
    s << indent << "speed_change: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed_change);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOFTCON_MESSAGE_TASKVAL_H
